name: pd2buildmanager
description: With this app you can create and edit builds for Payday 2

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/skill_logos/
    - assets/skill_logos/mastermind/
    - assets/skill_logos/mastermind/medic/
    - assets/skill_logos/mastermind/controller/
    - assets/skill_logos/mastermind/sharpshooter/
    - assets/skill_logos/enforcer/
    - assets/skill_logos/enforcer/shotgunner/
    - assets/skill_logos/enforcer/tank/
    - assets/skill_logos/enforcer/ammo_specialist/
    - assets/skill_logos/technician/
    - assets/skill_logos/technician/engineer/
    - assets/skill_logos/technician/breacher/
    - assets/skill_logos/technician/oppressor/
    - assets/skill_logos/ghost/
    - assets/skill_logos/ghost/shinobi/
    - assets/skill_logos/ghost/artful_dodger/
    - assets/skill_logos/ghost/silent_killer/
    - assets/skill_logos/fugitive/
    - assets/skill_logos/fugitive/gunslinger/
    - assets/skill_logos/fugitive/revenant/
    - assets/skill_logos/fugitive/brawler/

  uses-material-design: true